# Generated by Django 3.1.3 on 2021-02-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPR', '0003_auto_20210201_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policja',
            name='idPolicja',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='strazpozarna',
            name='idSzpital',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='szpital',
            name='idSzpital',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='zgloszenie',
            name='idZgloszenie',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
